import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import { homedir } from "os";
import { join } from "path";
import { discoverAgents } from "./agents.js";
import { runSingleAgent, runParallel, runChain } from "./subagent.js";

// ============================================================
// Workflow State
// ============================================================
// Tracks which phase the agent is in so before_agent_start
// can inject appropriate guidance into the system prompt.
// ============================================================

type WorkflowPhase =
  | "idle"
  | "clarifying"
  | "planning"
  | "ultraplanning";

let currentPhase: WorkflowPhase = "idle";

export default function (pi: ExtensionAPI) {
  // ============================================================
  // ask_user_question Tool
  // ============================================================
  // The agent calls this autonomously when it encounters ambiguity.
  // The agent generates the question text and choices dynamically.
  // ============================================================

  const DIRECT_INPUT_OPTION = "직접 입력하기";

  const AskUserQuestionParams = Type.Object({
    question: Type.String({
      description: "The question to ask the user. The agent generates this dynamically based on context.",
    }),
    choices: Type.Optional(
      Type.Array(Type.String(), {
        description:
          "Multiple choice options generated by the agent. '직접 입력하기' is auto-appended. Omit for free-text input.",
      })
    ),
    placeholder: Type.Optional(
      Type.String({
        description: "Placeholder hint for free-text input mode.",
      })
    ),
    defaultValue: Type.Optional(
      Type.String({
        description: "Default value if user presses Enter without typing.",
      })
    ),
  });

  pi.registerTool({
    name: "ask_user_question",
    label: "Ask User Question",
    description:
      "Ask the user a question when the agent needs clarification. The agent composes the question and optional choices dynamically. Returns the user's answer as text.",
    promptSnippet:
      "Ask the user a clarifying question with optional multiple-choice answers",
    promptGuidelines: [
      "Use ask_user_question whenever you encounter ambiguity, unclear scope, or need user preference.",
      "Generate the question and choices yourself based on the current context — do not rely on predefined templates.",
      "Offer concrete choices (A/B/C style) when the options are enumerable. Omit choices for open-ended questions.",
      "Ask one focused question at a time. Do not bundle multiple questions.",
      "After receiving an answer, decide whether further clarification is needed or proceed with the task.",
    ],
    parameters: AskUserQuestionParams,
    execute: async (toolCallId, params, signal, onUpdate, ctx) => {
      const { question, choices, placeholder, defaultValue } = params;

      let answer: string | undefined;

      if (choices && choices.length > 0) {
        const withDirect = choices.includes(DIRECT_INPUT_OPTION)
          ? choices
          : [...choices, DIRECT_INPUT_OPTION];

        answer = await ctx.ui.select(question, withDirect, { signal });

        if (answer === DIRECT_INPUT_OPTION) {
          answer = await ctx.ui.input(question, placeholder || defaultValue, {
            signal,
          });
        }
      } else {
        answer = await ctx.ui.input(question, placeholder || defaultValue, {
          signal,
        });
      }

      if (answer === undefined) {
        return {
          content: [{ type: "text", text: "User cancelled the question." }],
          details: undefined,
        };
      }

      return {
        content: [{ type: "text", text: answer }],
        details: undefined,
      };
    },
  });

  // ============================================================
  // subagent Tool
  // ============================================================
  // Delegates tasks to specialized agents running as separate
  // pi processes. Supports single, parallel, and chain modes.
  // ============================================================

  const TaskItem = Type.Object({
    agent: Type.String({
      description: "Name of the agent to invoke",
    }),
    task: Type.String({
      description: "Task to delegate to the agent",
    }),
    cwd: Type.Optional(
      Type.String({
        description: "Working directory for the agent process",
      })
    ),
  });

  const ChainItem = Type.Object({
    agent: Type.String({
      description: "Name of the agent to invoke",
    }),
    task: Type.String({
      description:
        "Task with optional {previous} placeholder for prior step output",
    }),
    cwd: Type.Optional(
      Type.String({
        description: "Working directory for the agent process",
      })
    ),
  });

  const SubagentParams = Type.Object({
    agent: Type.Optional(
      Type.String({
        description: "Agent name for single mode execution",
      })
    ),
    task: Type.Optional(
      Type.String({
        description: "Task description for single mode execution",
      })
    ),
    tasks: Type.Optional(
      Type.Array(TaskItem, {
        description:
          "Array of {agent, task} objects for parallel execution (max 8)",
      })
    ),
    chain: Type.Optional(
      Type.Array(ChainItem, {
        description:
          "Array of {agent, task} objects for sequential chaining. Use {previous} in task to reference prior output.",
      })
    ),
    agentScope: Type.Optional(
      Type.Unsafe<"user" | "project" | "both">({
        type: "string",
        enum: ["user", "project", "both"],
        description:
          'Which agent directories to search. "user" = ~/.pi/agent/agents/, "project" = .pi/agents/ in project root. Default: "user".',
        default: "user",
      })
    ),
    cwd: Type.Optional(
      Type.String({
        description: "Working directory for single mode",
      })
    ),
  });

  pi.registerTool({
    name: "subagent",
    label: "Subagent",
    description:
      "Delegate tasks to specialized agents running as separate pi processes. Supports single, parallel, and chain execution modes.",
    promptSnippet:
      "Delegate tasks to specialized agents (single, parallel, or chain mode)",
    promptGuidelines: [
      "Use single mode (agent + task) for one-off investigation or exploration tasks.",
      "Use parallel mode (tasks array) to dispatch multiple independent agents concurrently, e.g. codebase reviewers.",
      "Use chain mode (chain array) for sequential pipelines where each step uses {previous} to reference prior output.",
      "Agents are .md files with YAML frontmatter (name, description, tools, model) in ~/.pi/agent/agents/ (user) or .pi/agents/ (project).",
      "If the specified agent is not found, the task runs with default pi settings.",
      "Max 8 parallel tasks with 4 concurrent. Chain mode stops on first error.",
    ],
    parameters: SubagentParams,
    execute: async (toolCallId, params, signal, onUpdate, ctx) => {
      const { agent, task, tasks, chain, agentScope, cwd } = params;
      const defaultCwd = ctx.cwd;
      const agents = await discoverAgents(defaultCwd, agentScope || "user");
      const findAgent = (name: string) =>
        agents.find((a) => a.name === name);

      // Chain mode
      if (chain && chain.length > 0) {
        const steps = chain.map((s) => ({
          agent: findAgent(s.agent),
          task: s.task,
          cwd: s.cwd,
        }));
        const { finalResult, allResults } = await runChain(
          steps,
          defaultCwd,
          signal,
        );

        const summary = allResults
          .map(
            (r, i) =>
              `## Step ${i + 1}: ${chain[i].agent}\n**Status:** ${r.exitCode === 0 ? "Success" : "Failed"}\n\n${r.output}`,
          )
          .join("\n\n---\n\n");

        return {
          content: [
            {
              type: "text" as const,
              text: finalResult.error
                ? `Chain failed: ${finalResult.error}\n\n${summary}`
                : summary,
            },
          ],
          details: undefined,
        };
      }

      // Parallel mode
      if (tasks && tasks.length > 0) {
        const taskItems = tasks.map((t) => ({
          agent: findAgent(t.agent),
          task: t.task,
          cwd: t.cwd,
        }));
        const results = await runParallel(taskItems, defaultCwd, signal);

        const summary = results
          .map(
            (r, i) =>
              `## Agent: ${tasks[i].agent}\n**Task:** ${tasks[i].task}\n**Status:** ${r.exitCode === 0 ? "Success" : "Failed"}\n\n${r.output}`,
          )
          .join("\n\n---\n\n");

        return {
          content: [{ type: "text" as const, text: summary }],
          details: undefined,
        };
      }

      // Single mode
      if (agent && task) {
        const agentConfig = findAgent(agent);
        const result = await runSingleAgent(
          agentConfig,
          task,
          cwd || defaultCwd,
          signal,
        );

        return {
          content: [
            {
              type: "text" as const,
              text: result.error
                ? `Error: ${result.error}`
                : result.output,
            },
          ],
          details: undefined,
        };
      }

      return {
        content: [
          {
            type: "text" as const,
            text: "Error: Specify either (agent + task) for single mode, tasks for parallel mode, or chain for chain mode.",
          },
        ],
        details: undefined,
      };
    },
  });

  // ============================================================
  // resources_discover: Register engineering-discipline skills
  // ============================================================

  const SKILLS_DIR = join(homedir(), "engineering-discipline", "skills");

  pi.on("resources_discover", async (_event, _ctx) => {
    return {
      skillPaths: [SKILLS_DIR],
    };
  });

  // ============================================================
  // before_agent_start: Inject workflow phase guidance
  // ============================================================

  const PHASE_GUIDANCE: Record<WorkflowPhase, string> = {
    idle: "",
    clarifying: [
      "\n\n## Active Workflow: Clarification",
      "You are in clarification mode. Follow the clarification skill rules strictly:",
      "- Ask ONE question per message using the ask_user_question tool.",
      "- Generate questions and choices dynamically based on context — no predefined templates.",
      "- Use the subagent tool in single mode to explore the codebase in parallel with user Q&A.",
      "- After each answer, update 'what we've established so far' and assess remaining ambiguity.",
      "- When ambiguity is resolved, present a Context Brief with Complexity Assessment.",
      "- Do NOT start implementation. This phase ends with a Context Brief, not code.",
    ].join("\n"),
    planning: [
      "\n\n## Active Workflow: Plan Crafting",
      "You are in plan-crafting mode. Follow the plan-crafting skill rules strictly:",
      "- Write an executable implementation plan from the current context.",
      "- Every step must be executable — no placeholders.",
      "- Use ask_user_question if you need to resolve any remaining ambiguity.",
      "- End with a Self-Review before presenting the plan.",
    ].join("\n"),
    ultraplanning: [
      "\n\n## Active Workflow: Milestone Planning (Ultraplan)",
      "You are in milestone-planning mode. Follow the milestone-planning skill rules strictly:",
      "- Compose a Problem Brief from the current context.",
      "- Dispatch all 5 reviewer agents in parallel using the subagent tool's parallel mode.",
      "- The 5 reviewers are: Feasibility, Architecture, Risk, Dependency, and User Value analysts.",
      "- Synthesize all reviewer findings into a milestone DAG.",
      "- Use ask_user_question if you need user input on trade-offs.",
    ].join("\n"),
  };

  pi.on("before_agent_start", async (event, _ctx) => {
    const guidance = PHASE_GUIDANCE[currentPhase];
    if (!guidance) return;
    return {
      systemPrompt: event.systemPrompt + guidance,
    };
  });

  // ============================================================
  // Commands
  // ============================================================

  pi.registerCommand("clarify", {
    description:
      "Start clarification — the agent asks dynamic questions to resolve ambiguity",
    handler: async (args, ctx) => {
      const topic = args?.trim() || "";
      const start = await ctx.ui.confirm(
        "Start Clarification",
        "The agent will ask you questions one at a time to clarify your request.\nIt will also explore the codebase in parallel.\n\nProceed?"
      );
      if (!start) return;

      currentPhase = "clarifying";
      ctx.ui.setStatus("harness", "Clarification in progress...");

      const prompt = topic
        ? `The user wants to clarify the following request: "${topic}"\n\nBegin the clarification process. Follow the clarification skill rules. Ask ONE question using the ask_user_question tool. Use the subagent tool in single mode to investigate relevant parts of the codebase in parallel.`
        : `The user wants to start a clarification session for their current task.\n\nBegin the clarification process. Follow the clarification skill rules. Ask ONE question using the ask_user_question tool to understand what the user wants to accomplish. Use the subagent tool in single mode to investigate the codebase in parallel.`;

      pi.sendUserMessage(prompt);
    },
  });

  pi.registerCommand("plan", {
    description:
      "Generate an implementation plan — the agent follows plan-crafting skill rules",
    handler: async (args, ctx) => {
      const ok = await ctx.ui.confirm(
        "Start Plan Crafting",
        "The agent will create an executable implementation plan based on current context.\n\nProceed?"
      );
      if (!ok) return;

      currentPhase = "planning";
      ctx.ui.setStatus("harness", "Plan crafting in progress...");

      const topic = args?.trim() || "";
      const prompt = topic
        ? `Create an executable implementation plan for: "${topic}"\n\nFollow the plan-crafting skill rules. If a Context Brief exists from a previous clarification, use it as input. If not, use the ask_user_question tool to confirm goal, scope, and tech stack before writing the plan.`
        : `Create an executable implementation plan for the current task.\n\nFollow the plan-crafting skill rules. If a Context Brief exists from a previous clarification, use it as input. If not, use the ask_user_question tool to confirm goal, scope, and tech stack before writing the plan.`;

      pi.sendUserMessage(prompt);
    },
  });

  pi.registerCommand("ultraplan", {
    description:
      "Decompose a complex task into milestones — the agent dynamically selects reviewers",
    handler: async (args, ctx) => {
      const confirmed = await ctx.ui.confirm(
        "Start Milestone Planning (Ultraplan)",
        "The agent will:\n1. Compose a Problem Brief\n2. Decide which reviewer perspectives are needed\n3. Dispatch reviewers in parallel\n4. Synthesize a milestone DAG\n\nProceed?"
      );
      if (!confirmed) return;

      currentPhase = "ultraplanning";
      ctx.ui.setStatus("harness", "Milestone planning in progress...");

      const topic = args?.trim() || "";
      const prompt = topic
        ? `Decompose the following complex task into milestones: "${topic}"\n\nFollow the milestone-planning skill rules. First compose a Problem Brief. Then dispatch all 5 reviewer agents (Feasibility, Architecture, Risk, Dependency, User Value) in parallel using the subagent tool's parallel mode. After all reviewers complete, synthesize their findings into a milestone DAG.`
        : `Decompose the current complex task into milestones.\n\nFollow the milestone-planning skill rules. First compose a Problem Brief from the current context. Then dispatch all 5 reviewer agents (Feasibility, Architecture, Risk, Dependency, User Value) in parallel using the subagent tool's parallel mode. After all reviewers complete, synthesize their findings into a milestone DAG.`;

      pi.sendUserMessage(prompt);
    },
  });

  // ============================================================
  // /ask — manual test command for ask_user_question
  // ============================================================

  pi.registerCommand("ask", {
    description: "Ask the user a question (for testing the ask_user_question tool)",
    handler: async (args, ctx) => {
      const question = await ctx.ui.input(
        "Enter a question",
        args || "What would you like to know?"
      );
      if (!question) return;

      const choicesStr = await ctx.ui.input(
        "Enter comma-separated choices (leave empty for free text)",
        ""
      );
      const choices = choicesStr
        ? choicesStr.split(",").map((s) => s.trim()).filter(Boolean)
        : undefined;

      let answer: string | undefined;
      if (choices && choices.length > 0) {
        answer = await ctx.ui.select(question, choices);
      } else {
        answer = await ctx.ui.input(question);
      }

      if (answer !== undefined) {
        ctx.ui.notify(`Answer: ${answer}`, "info");
      }
    },
  });

  // ============================================================
  // /reset-phase — reset workflow phase to idle
  // ============================================================

  pi.registerCommand("reset-phase", {
    description: "Reset the workflow phase to idle (clears clarify/plan/ultraplan mode)",
    handler: async (_args, ctx) => {
      currentPhase = "idle";
      ctx.ui.setStatus("harness", undefined);
      ctx.ui.notify("Workflow phase reset to idle.", "info");
    },
  });

  // ============================================================
  // Session start notification
  // ============================================================

  pi.on("session_start", async (_event, ctx) => {
    currentPhase = "idle";
    ctx.ui.notify(
      "Agentic Harness loaded: /clarify, /plan, /ultraplan, /ask, /reset-phase",
      "info"
    );
  });
}
